import { z } from "zod";
export const hexColorSchema = z.string().regex(/^#([0-9A-Fa-f]{6})$/, "Informe uma cor hexadecimal válida. Ex: #2563EB");
export const registerSchema = z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(6),businessName:z.string().min(2),phone:z.string().optional()});
export const loginSchema = z.object({email:z.string().email(),password:z.string().min(6)});
export const serviceSchema = z.object({name:z.string().min(2),description:z.string().optional(),durationMins:z.number().int().min(1),price:z.coerce.number().min(0),active:z.boolean().optional()});
export const professionalSchema = z.object({name:z.string().min(2),role:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional().or(z.literal("")),avatarUrl:z.string().url().optional().or(z.literal("")),color:hexColorSchema.optional(),active:z.boolean().optional()});
export const clientSchema = z.object({name:z.string().min(2),phone:z.string().optional(),email:z.string().email().optional().or(z.literal("")),notes:z.string().optional()});
export const appointmentSchema = z.object({clientId:z.string().optional(),clientName:z.string().optional(),clientPhone:z.string().optional(),serviceId:z.string(),professionalId:z.string().optional(),date:z.coerce.date(),endDate:z.coerce.date().optional(),notes:z.string().optional()}).superRefine((v,ctx)=>{if(!v.clientId&&!v.clientName)ctx.addIssue({code:"custom",message:"clientId ou clientName é obrigatório"});if(v.date<new Date())ctx.addIssue({code:"custom",message:"Data não pode estar no passado"});});
export const settingsSchema = z.object({businessName:z.string().min(2),slug:z.string().min(2),phone:z.string().optional(),whatsappPhone:z.string().optional(),whatsappProvider:z.enum(["EVOLUTION","TWILIO"]).optional(),remindersEnabled:z.boolean(),reminderMinutesBefore:z.number().int().min(5),openingHours:z.any().optional(),primaryColor:hexColorSchema,secondaryColor:hexColorSchema.optional().or(z.literal("")),publicTitle:z.string().optional(),publicDescription:z.string().optional(),logoUrl:z.string().url().optional().or(z.literal(""))});
